management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator  
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

server:
    port: 8761
    connection-timeout: 600s
    tomcat:
       max-threads: 8000       
       min-spare-threads: 15
       accept-count: 600
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 2048  
      
spring:
  application:
    name: eureka


eureka:  
  instance:
    hostname: eureka 
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 3 
  server:
    eviction-interval-timer-in-ms: 90000 #default 60000
    response-cache-update-interval-ms: 30000 #default 30000
    a-sgcache-expiry-timeout-ms: 30000
    peer-eureka-nodes-update-interval-ms: 15000
    renewal-threshold-update-interval-ms: 30000
    use-read-only-response-cache: false
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0
    peer-node-read-timeout-ms: 10000  
  client:
    healthcheck:
     enabled: true  
    register-with-eureka: false
    fetch-registry: true
    healthcheck.enabled: true    
