management:
  security:
    enabled: false
  server:
    port: 24010
    base-path: /management
  tracing:
    sampling:
      probability: 1.0 
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
    shutdown: GRACEFUL
    http2:
     enabled: true
    port: 24000
    servlet:
      session:
        timeout: 10m
    undertow:
      buffer-size: 80960
      no-request-timeout: 15000  
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024 
spring: 
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false
  application:
    name: eventcare
    
  kafka:   
    listener:
      ack-mode: MANUAL  
    consumer:
      bootstrap-servers: kafka1:9092,kafka2:9093
      group-id: event-duty
      auto-offset-reset: earliest         
      enable-auto-commit: false
      session.timeout.ms: 30000
      max-poll-records: 10
      fetch-max-wait: 100
      fetch-min-size: 504857600
      
  profiles:
    active: prod
  threads:
    virtual:
      enabled: true
    
  flyway:
    enabled: true

  datasource:
    hikari:
      # Connection pool settings for HikariCP
      connection-timeout: 30000           # Maximum time that a client will wait for a connection from the pool (in milliseconds)
      idle-timeout: 60000                 # Maximum time that a connection is allowed to sit idle in the pool (in milliseconds)
      max-lifetime: 18000                 # Maximum lifetime of a connection in the pool (in milliseconds)
      maximum-pool-size: 200              # Maximum number of connections that can be maintained in the pool
      minimum-idle: 5                     # Minimum number of idle connections that HikariCP tries to maintain in the pool
      pool-name: carelake                 # Name of the connection pool

    tomcat:
      # Connection pool settings for Tomcat JDBC
      initial-size: 50                    # Initial number of connections that are created when the pool is started
      max-wait: 80000                     # The maximum time (in milliseconds) that the pool will wait for a connection to be returned
      max-active: 800                     # The maximum number of active connections that can be allocated from the pool
      max-idle: 100                       # The maximum number of connections that can remain idle in the pool
      min-idle: 30                        # The minimum number of idle connections that Tomcat JDBC tries to maintain in the pool
      remove-abandoned: true              # Whether to remove abandoned connections (true/false)
      remove-abandoned-timeout: 800       # Timeout (in seconds) before a connection is considered abandoned
      time-between-eviction-runs-millis: 3400000  # The time between runs of the idle connection eviction thread (in milliseconds)
      min-evictable-idle-time-millis: 5500000    # The minimum time a connection may sit idle in the pool before it is eligible for eviction (in milliseconds)
      default-auto-commit: false          # Default auto-commit behavior for connections obtained from the pool

    url: '${POSTGRES_URI:jdbc:postgresql://timescale:5432/healthcare}'  # JDBC URL for connecting to the database
    username: '${POSTGRES_USER:healthcare}'                             # Database username
    password: '${POSTGRES_PASSWORD:healthcare}'                         # Database password
    platform: POSTGRESQL                 # Platform name (e.g., POSTGRESQL, H2, MYSQL)
    test-while-idle: true                # Test connections while they are idle
    validation-query: SELECT 1           # SQL query used to validate connections
    driver-class-name: org.postgresql.Driver  # Fully qualified name of the JDBC driver class

  jpa:
    show-sql: false                      # Whether to show SQL statements in the console
    database: POSTGRESQL                 # Database dialect to use (e.g., POSTGRESQL, H2, MYSQL)
    hibernate:
      ddl-auto: none                  # Hibernate DDL strategy (e.g., create, update, validate, none)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # Naming strategy for Hibernate
      dialect: org.hibernate.dialect.PostgreSQL10Dialect         # Database dialect for Hibernate
      query:
        plan-cache-max-size: 4096        # Maximum size of the query plan cache
        plan-parameter-metadata-max-size: 8192  # Maximum size of the query plan parameter metadata cache
    properties:
      hibernate:
        temp:
          use-jdbc-metadata-defaults: false  # Whether to use JDBC metadata defaults for handling temporal types

  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
    level:
      root: INFO
      io.project: INFO
        
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
    appname: eventcare
    instanceId: eventcare:${spring.application.instance-id:${random.value}}
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
      
      
